### ISSUE TITLE
[zen]Error: Cannot find module '../../../.pnp.js'

### ISSUE THREAD

**Issue by veeramarni** [sysgears/larix#10]
Getting the following error with the latest version. Seems to be a build or npm packaging issue.

```
> zen  watch

internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module '../../../.pnp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users//fullstack-pro/node_modules/@larix/zen/src/boot-dev.js:1:63)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by larixer** [comment]
@veeramarni Thanks, should be fixed now

**Comment by veeramarni** [comment]
@larixer  thanks for fixing it quickly.
