### ISSUE TITLE
Functionality to ignore folders for BuilderDiscoverer / bug report

### ISSUE THREAD

**Issue by TeNNoX** [sysgears/larix#20]
BuilderDiscoverer seems to scan all directories recursively. There should be a functionality to ignore certain folders, as there might be:

- a huge number of files, causing performance issues
- or, in my case, a permisions issue:

```
> zen start

zen error Error: EACCES: permission denied, scandir '/home/manu/stuff/our-board/backend/docker/local-nextcloud/db/mysql'
    at Object.readdirSync (fs.js:955:3)
    at BuilderDiscoverer._discoverRecursively (/home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/BuilderDiscoverer.ts:40:22)
    at BuilderDiscoverer._discoverRecursively (/home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/BuilderDiscoverer.ts:44:43)
    at BuilderDiscoverer._discoverRecursively (/home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/BuilderDiscoverer.ts:44:43)
    at BuilderDiscoverer._discoverRecursively (/home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/BuilderDiscoverer.ts:44:43)
    at BuilderDiscoverer._discoverRecursively (/home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/BuilderDiscoverer.ts:44:43)
    at /home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/BuilderDiscoverer.ts:25:32
    at Array.reduce (<anonymous>)
    at BuilderDiscoverer.discover (/home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/BuilderDiscoverer.ts:24:29)
    at Object.createBuilders [as default] (/home/manu/stuff/our-board/backend/node_modules/@larix/zen/src/createBuilders.ts:82:44) {
  errno: -13,
  syscall: 'scandir',
  code: 'EACCES',
  path: '/home/manu/stuff/our-board/backend/docker/local-nextcloud/db/mysql'
}
```

**Comment by larixer** [comment]
@TeNNoX Would you be willing to submit a Pull Request to implement this?
