### ISSUE TITLE
latest version fails

### ISSUE THREAD

**Issue by veeramarni** [sysgears/larix#25]
After the recent PR we getting following errors

```error
Error: Cannot find module '../../../.pnp.js'
Require stack:
- /Users/common/fullstack-pro/node_modules/@larix/zen/src/boot-dev.js
- /Users/common/fullstack-pro/node_modules/@larix/zen/src/boot-cli-dev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/veeramarni/common/fullstack-pro/node_modules/@larix/zen/src/boot-dev.js:1:1)
```

**Comment by larixer** [comment]
@veeramarni Sorry, I forgot how to publish it, published `@larix/zen@0.1.37`, it should work
